server:
  port: 8087
spring: 
  datasource: 
    driver-class-name: com.mysql.jdbc.Driver
    password: root
    tomcat: 
      default-auto-commit: true
      initial-size: 20
      max-active: 50
      max-idle: 15
      max-wait: 20000
    url: "jdbc:mysql://localhost:3306/test"
    username: root
  jpa: 
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate: 
      ddl-auto: update
    properties: 
      hibernate: 
        enable_lazy_load_no_trans: true
        format_sql: true
    show-sql: true
